In [2]:
import json
import pandas as pd

In [3]:
path = "D:\schule\diplomarbeit\MPD\MPD\mpd.slice.0-999.json"

In [4]:
f = open(path)
js = f.read()
f.close()
mpd_slice = json.loads(js)

In [52]:
playlists = mpd_slice['playlists'][0:5]

In [53]:
playlist_names = (playlist['name'] for playlist in playlists)
for playlist in playlist_names:
    print(playlist)

Throwbacks
Awesome Playlist
korean 
mat
90s


In [55]:
import csv

with open('mpd_file.csv', mode='w', encoding='utf-8') as mpd_file:
    writer = csv.writer(mpd_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    #writer.writerow(['John Smith', 'Accounting', 'November'])
    for playlist in playlists:
        playlist_name = playlist['name']
        for track in playlist['tracks']:
            track_name = track['track_name']
            #print(f'{playlist_name}: {track_name}')
            writer.writerow([playlist_name, track_name, 1])


In [64]:
csv_path = "D:\schule\diplomarbeit\mpd_file10000.csv"

In [65]:
playlists = pd.read_csv(csv_path,  delimiter=',', encoding='utf-8',
                     usecols=(0,1,2), names=('playlist','track', "in"), header=None)
playlists.head()

playlist                                       track  in
0  Throwbacks  Lose Control (feat. Ciara & Fat Man Scoop)   1
1  Throwbacks                                       Toxic   1
2  Throwbacks                               Crazy In Love   1
3  Throwbacks                              Rock Your Body   1
4  Throwbacks                                It Wasn't Me   1

In [66]:
len(playlists)

67503

In [67]:
from fastai.collab import *
from fastai.tabular.all import *

Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe


In [68]:
dls = CollabDataLoaders.from_df(playlists, item_name='track', bs=64)

In [69]:
dls.show_batch()

In [70]:
dls.classes

{'playlist': (#870) ['#na#',' CHiLl',' Frozen',' indie rock','#Relaxed','#Workout','#boostyourrun','#chill','#mood','( ͡° ͜ʖ ͡°)'...],
 'track': (#30050) ['#na#','"40" - Remastered 2008','"45"','"A Lovely Night"','"A Lovely Night" (Reprise)','"Can\'t Repeat The Past?"','"Do I Love You Because You\'re Beautiful"','"Esh \'Dani, Alash Mshit"','"Gatsby Believed In The Green Light"','"He Was Tall"'...]}

In [83]:
learn = collab_learner(dls, n_factors=5, y_range=(0, 1))

In [84]:
learn.fit_one_cycle(10, 5e-3)

In [85]:
track_factors = learn.model.i_weight.weight
idx = dls.classes['track'].o2i['Lip Gloss']
distances = nn.CosineSimilarity(dim=1)(track_factors, track_factors[idx][None])
idx = distances.argsort(descending=True)[1]
dls.classes['track'][idx]

'Check On It - feat. Bun B and Slim Thug'

In [86]:
track_factors

Parameter containing:
tensor([[ 0.0022,  0.0033, -0.0022,  0.0099, -0.0089],
        [-0.0268,  0.0070,  0.0326,  0.0283, -0.0245],
        [-0.0359,  0.0005,  0.0249,  0.0400, -0.0256],
        ...,
        [ 0.0371,  0.0342,  0.0246, -0.0063,  0.0050],
        [ 0.0402,  0.0331,  0.0403, -0.0094,  0.0284],
        [ 0.0378,  0.0247,  0.0283, -0.0313,  0.0129]], requires_grad=True)

In [87]:
playlist_factors = learn.model.u_weight.weight

In [88]:
playlist_factors[0].t()

tensor([ 0.0091, -0.0135, -0.0050, -0.0058,  0.0063], grad_fn=<TBackward>)

In [89]:
track_factors[0] @ playlist_factors[0]

tensor(-0.0001, grad_fn=<DotBackward>)

In [90]:
idx = dls.classes['playlist'].o2i['Awesome Playlist']
idx

2

In [91]:
playlist_factors[2]

tensor([ 0.0636,  0.0603,  0.0566,  0.0677, -0.0706], grad_fn=<SelectBackward>)

In [99]:
distances = list((playlist_factors[2] @ track_factor for track_factor in track_factors))

In [100]:
len(distances)

298

In [102]:
index_max = np.argmax(distances)
index_max

279

In [104]:
dls.classes['track'][index_max]

'YYZ'

In [109]:
test = np.array([8, 2, 4, 4, 5, 7, 9])
test2 = np.array([3, 4, 5])

In [78]:
test @ test2

31

In [111]:
idx = np.argpartition(test, -2)[-2:]
indices = idx[np.argsort((-test)[idx])]
print(indices)

[6 0]


In [58]:
playlists = mpd_slice['playlists'][0:1000]

In [59]:
filtered = list(filter(lambda x: x['name'] == "#boostyourrun", playlists))

In [61]:
len(filtered)

1

In [62]:
tracks = list((track['track_name'] for track in filtered[0]['tracks']))

In [63]:
tracks

['Many the Miles',
 'Love Me Like That (Karaoke Version) - Originally Performed By Michelle Branch & Sheryl Crow',
 'Lucky',
 'Human Of The Year',
 'Every Single Night',
 'Thinking About You',
 'Radio Radio',
 'Glamour Puss',
 "I'm Yours",
 'Where Are You Now?',
 '#boostyourrun',
 'Blame, Blame, Blame',
 'Good Is Good',
 "Pony (It's OK)",
 'Queen of California',
 'Everybody',
 'Almost Lover',
 '1234',
 'Wild Horses',
 'Featherwoman',
 '1963',
 'Until I Die']

In [1]:
import random as rd

In [4]:
for n in range(0, 10):
    print(rd.randint(1, 5))

5
1
3
2
1
5
5
2
4
5


In [1]:
from flask import Flask

In [3]:
app = Flask("flowsy")

@app.route('/')
def example():
    return '{"name": "Bob"}'

app.run()

 * Serving Flask app "flowsy" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
